import React, { useEffect, useState } from 'react';
import { Users, CreditCard, ArrowLeftRight, ShieldCheck, TrendingUp, AlertCircle, Activity, ArrowUpRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { dashboardAPI } from '../../api';
import StatsCard from '../../components/ui/StatsCard';
import VolumeChart from '../../components/charts/VolumeChart';
import TransactionTable from '../../components/charts/TransactionTable';
import { CardSkeleton, TableSkeleton } from '../../components/skeletons/Skeletons';
import { formatCurrency, getErrorMessage } from '../../utils/formatters';
import toast from 'react-hot-toast';

const AdminDashboard = () => {
  const [stats, setStats] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { dashboardAPI.getStats().then((d) => setStats(d.data)).catch((err) => toast.error(getErrorMessage(err))).finally(() => setLoading(false)); }, []);
  const pending = (stats?.accounts?.pending ?? 0) + (stats?.kyc?.pending ?? 0);
  return <div className="space-y-6">
    <section className="premium-card p-6 sm:p-7 bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 text-white border-0 shadow-xl"><div className="absolute -right-24 -top-24 w-80 h-80 bg-blue-500/15 rounded-full blur-3xl" /><div className="relative flex flex-col md:flex-row md:items-end md:justify-between gap-5"><div><div className="inline-flex items-center gap-2 rounded-full bg-white/10 border border-white/10 px-3 py-1.5 text-xs text-slate-300"><Activity className="w-3.5 h-3.5 text-blue-300" /> System control center</div><h2 className="text-3xl sm:text-4xl font-bold tracking-tight mt-4">Admin Dashboard</h2><p className="text-slate-300 mt-2">Monitor users, accounts, transactions and compliance activity.</p></div><div className="rounded-2xl bg-white/10 border border-white/10 px-5 py-4 min-w-[190px]"><p className="text-xs text-slate-400">Items requiring attention</p><p className="text-3xl font-bold mt-1">{loading ? '—' : pending}</p><p className="text-xs text-blue-300 mt-1">Accounts + KYC</p></div></div></section>
    {loading ? <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{[...Array(8)].map((_, i) => <CardSkeleton key={i} />)}</div> : <><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatsCard title="Total Users" value={stats?.users?.total ?? 0} subtitle={`${stats?.users?.customers ?? 0} customers · ${stats?.users?.employees ?? 0} employees`} icon={Users} iconBg="bg-blue-100 dark:bg-blue-900/30" iconColor="text-blue-600 dark:text-blue-400" /><StatsCard title="Total Accounts" value={stats?.accounts?.total ?? 0} subtitle={`${stats?.accounts?.pending ?? 0} pending`} icon={CreditCard} iconBg="bg-purple-100 dark:bg-purple-900/30" iconColor="text-purple-600 dark:text-purple-400" /><StatsCard title="Transactions" value={stats?.transactions?.total ?? 0} subtitle="All time" icon={ArrowLeftRight} iconBg="bg-green-100 dark:bg-green-900/30" iconColor="text-green-600 dark:text-green-400" /><StatsCard title="Pending KYC" value={stats?.kyc?.pending ?? 0} subtitle="Awaiting review" icon={ShieldCheck} iconBg="bg-yellow-100 dark:bg-yellow-900/30" iconColor="text-yellow-600 dark:text-yellow-400" /></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><StatsCard title="Deposit Volume" value={formatCurrency(stats?.transactions?.totalDeposits ?? 0)} icon={TrendingUp} iconBg="bg-emerald-100 dark:bg-emerald-900/30" iconColor="text-emerald-600" /><StatsCard title="Withdrawal Volume" value={formatCurrency(stats?.transactions?.totalWithdrawals ?? 0)} icon={TrendingUp} iconBg="bg-red-100 dark:bg-red-900/30" iconColor="text-red-600" /><StatsCard title="Active Accounts" value={stats?.accounts?.active ?? 0} icon={CreditCard} iconBg="bg-teal-100 dark:bg-teal-900/30" iconColor="text-teal-600" /><StatsCard title="Pending Approvals" value={pending} icon={AlertCircle} iconBg="bg-orange-100 dark:bg-orange-900/30" iconColor="text-orange-600" /></div></>}
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-6"><div className="xl:col-span-2"><VolumeChart data={stats?.transactionVolume || []} title="7-Day Transaction Volume" /></div><div className="card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-bold text-gray-800 dark:text-white">System summary</h3><p className="text-xs text-gray-400 mt-1">Current operating snapshot</p></div><Link to="/admin/audit" className="text-xs text-primary-600 font-bold">Audit logs</Link></div><div className="space-y-1">{[['Customers', stats?.users?.customers ?? 0], ['Employees', stats?.users?.employees ?? 0], ['Active accounts', stats?.accounts?.active ?? 0], ['Pending approvals', pending], ['Transfer volume', formatCurrency(stats?.transactions?.totalTransferOut ?? 0)]].map(([label,value]) => <div key={label} className="flex justify-between py-3 border-b border-gray-100 dark:border-banking-border last:border-0"><span className="text-sm text-gray-500 dark:text-gray-400">{label}</span><span className="text-sm font-bold text-gray-900 dark:text-white">{value}</span></div>)}</div></div></div>
    <div className="card p-5"><div className="flex items-center justify-between mb-4"><div><h3 className="font-bold text-gray-800 dark:text-white">Recent transactions</h3><p className="text-xs text-gray-400 mt-1">Latest system activity</p></div><Link to="/admin/transactions" className="inline-flex items-center gap-1 text-xs text-primary-600 font-bold">View all <ArrowUpRight className="w-3.5 h-3.5" /></Link></div>{loading ? <TableSkeleton rows={6} cols={6} /> : <TransactionTable transactions={stats?.recentTransactions || []} showAccount />}</div>
  </div>;
};
export default AdminDashboard;
